plugins:
  - mergePaths: true
  - transformsWithOnePath: true
  - removeTitle: true
  - removeXMLNS: true
  - removeDimensions: true
  - sortAttrs: true
  - removeStyleElement: true
  - removeScriptElement: true
  - removeAttrs:
      attrs: ['stroke', 'fill', 'style', 'xmlns', 'xmlns:xlink']

js2svg:
  pretty: true
  indent: '  '
